[phases.setup]
nixPkgs = ["nodejs", "python310", "python310Packages.pip"]

[phases.install]
cmds = [
  "npm install",
  "python3.10 -m pip install -r requirements.txt"
]

[start]
cmd = "npm run start"
