[phases.setup]
nixPkgs = ["nodejs", "python310"] # Only need python310 and nodejs

[phases.install]
cmds = [
  "npm install",
  "python3.10 -m venv .venv", # Create a virtual environment named .venv
  "source .venv/bin/activate", # Activate the virtual environment
  "pip install --upgrade pip setuptools wheel", # Upgrade pip and essential tools within the venv
  "pip install -r requirements.txt" # Install your project dependencies within the venv
]

[start]
cmd = "source .venv/bin/activate && npm run start" # IMPORTANT: Activate venv for start command too
