[phases.setup]
nixPkgs = ["nodejs"] # Remove all Python-related packages from nixPkgs

[phases.install]
cmds = [
  "npm install",
  # Add a specific Python executable to the PATH and ensure pip is there
  "nix-shell -p python310 --run 'python3.10 -m ensurepip --default-pip'", # This attempts to get a python3.10 with ensurepip
  "nix-shell -p python310 --run 'python3.10 -m pip install --upgrade pip setuptools wheel'", # Upgrade pip and essential tools
  "nix-shell -p python310 --run 'python3.10 -m pip install -r requirements.txt'" # Install your project dependencies
]

[start]
cmd = "npm run start"
