[phases.setup]
nixPkgs = ["nodejs", "python310", "curl"] # Add python310 back, and 'curl' to download get-pip.py

[phases.install]
cmds = [
  "npm install",
  # Download and run get-pip.py to ensure pip is installed
  "curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "python3.10 get-pip.py --force-reinstall", # Force reinstall pip for python3.10
  "rm get-pip.py", # Clean up the script
  "python3.10 -m pip install --upgrade pip setuptools wheel", # Upgrade pip and install essential build tools
  "python3.10 -m pip install -r requirements.txt" # Finally, install your project dependencies
]

[start]
cmd = "npm run start"
