[phases.setup]
nixPkgs = ["python3"]
# REMOVED: nodeJs = "22" - Let Nixpacks auto-detect Node.js setup

[phases.install]
cmds = ["npm install"] # Keep this to ensure npm dependencies are installed

[start]
cmd = "npm run start"
